### ISSUE TITLE
operation_mode not found in /Sounding ?

### ISSUE THREAD

**Issue by vwgeiser** [hcronk/oco2_modis_vistool#21]
Hello all, very new oco user here, I have followed the installations instructions in the readme but when I try to run test case with the minimum function call (step 3 in readme) I get:

```
(oco_vistool) vwgeiser@MACHINENAME:~/Documents/oco3/oco2_modis_vistool$ python oco_vistool.py
Either there was no output plot location specified or the one specified does not exist. Plot output will go in the code directory.

Either there was no output data location specified or the one specified does not exist. Data output will go in the code directory.

Using default cmap viridis for var_name: xco2
Output plot will include all quality soundings

Traceback (most recent call last):
  File "/home/vwgeiser/Documents/oco3/oco2_modis_vistool/oco_vistool.py", line 1429, in <module>
    odat = load_OCO2_Lite_overlay_data(ovr_d)
  File "/home/vwgeiser/Documents/oco3/oco2_modis_vistool/oco_vistool.py", line 990, in load_OCO2_Lite_overlay_data
    lite_operation_mode = lite_file.get_operation_mode()
  File "/home/vwgeiser/Documents/oco3/oco2_modis_vistool/OCO2FileOps.py", line 141, in get_operation_mode
    opmode_code = self.lf['/Sounding/operation_mode'][:]
  File "src/netCDF4/_netCDF4.pyx", line 2386, in netCDF4._netCDF4.Dataset.__getitem__
IndexError: operation_mode not found in /Sounding
```

I will mainly be looking at SAMs, do I have to add this in the function call? I am using a miniconda enviornment. I am also using a windows subsystem for linux so perhaps this is a problem with my installation?

**Comment by hcronk** [comment]
Hi Victor,

`operation_mode` is specifically a field in the Lite Files, but it's really just used to construct the output filename and add metadata to the file. If you wanted to add flexibility for the SAMs, you can fork and submit a pull request, and if you would prefer to have me make the update, can you provide an example input file?

Thanks,
Heather

**Comment by vwgeiser** [comment]
Hey Heather, 

I wasn't providing it an input file because I was just trying to run the test case? but it is my understanding that `operation_mode` is a data variable within the /Sounding variable group? Where `operation_mode == 4' means SAM operation mode.

![image](https://github.com/user-attachments/assets/7e9068f8-ee00-4df0-8349-72d6ae452617)

Here is an example file, uploaded as a zip because GitHub doesn't let me attach a .nc4 file
[oco3_LtCO2_190910_B10400Br_220317234607s.zip](https://github.com/user-attachments/files/16616224/oco3_LtCO2_190910_B10400Br_220317234607s.zip)

**Comment by hcronk** [comment]
Sure enough! SAMs were not in the OCO2 concept but it makes perfect sense that that'd be an operation mode for OCO-3. Thank you for providing the input example. I will have time to incorporate this capability in a few weeks (Labor Day weekend), are you able to wait?

**Comment by vwgeiser** [comment]
I am certainly able to wait, thanks for looking into this.

**Comment by hcronk** [comment]
Hi Victor,

Can you test the fix in the `21-operation_mode-not-found-in-sounding` branch? I'll merge to main once you confirm it works for you.

FWIW, I got a request timeout error from Worldview the first time I ran it, but re-ran and was able to complete successfully

Heather

**Comment by vwgeiser** [comment]
Hey Heather,

Just tried it with the `21-operation_mode-not-found-in-sounding` branch. It looks good thanks for looking into it! I've attached my output that has a couple "Possible Issues" for your reference.

`python oco_vistool.py`

```
Either there was no output plot location specified or the one specified does not exist. Plot output will go in the code directory.

Either there was no output data location specified or the one specified does not exist. Data output will go in the code directory.

Using default cmap viridis for var_name: xco2
Output plot will include all quality soundings

Possible issue encountered when converting Shape #95 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #95 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #491 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #491 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #1544 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #1544 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Requested time from Worldview:  2016-07-27T18:19:13Z

Figure saved at MODIS_Aqua_CorrectedReflectance_TrueColor_20160727.png
Possible issue encountered when converting Shape #95 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #95 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #491 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #491 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #1544 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Possible issue encountered when converting Shape #1544 to GeoJSON: Shapefile format requires that polygons contain at least one exterior ring, but the Shape was entirely made up of interior holes (defined by counter-clockwise orientation in the shapefile format). The rings were still included but were encoded as GeoJSON exterior rings instead of holes.
Requested time from Worldview:  2016-07-27T18:19:13Z

Figure saved at MODIS_Aqua_CorrectedReflectance_TrueColor_xco2_20160727_B99999r.png
```

![MODIS_Aqua_CorrectedReflectance_TrueColor_xco2_20160727_B99999r](https://github.com/user-attachments/assets/a4be57c6-35e6-49f0-a747-238cd236aa62)
